HDA-10071 [공통] GitHub Action을 통해 PR을 만들어도 앱을 빌드하도록 개선
PRNDcompany/prnd-android-workflows pull request #37
Opened 2023-09-06 07:20 UTC by olaf-prnd

## 개요
github-actions가 만드는 PR은 workflow event를 트리거하지 않습니다. 
이를 해결하기 위해 별도 계정으로 PR을 생성하도록 만들도록 변경합니다.

이 작업 이후로 아래와 같이 변경됩니다.

- as-is
  - PR Create: github-actions
  - PR Approve: 별도 계정
- to-be
  - PR Create: 별도 계정
  - PR Approve:  github-actions

## 관련 채널 내용

https://prnd.slack.com/archives/C9UERACB1/p1693969335067949

2023-09-06 08:52 UTC, ted-prnd requested changes

2023-09-06 08:52 UTC, ted-prnd commented on .github/workflows/release_pr_create.yml
> +      CREATOR_ACCESS_TOKEN:
보통 PAT를 일반적으로 사용하고 있으니 `PERSONAL`로 해도 될것 같습니다.

2023-09-07 04:48 UTC, olaf-prnd commented on .github/workflows/release_pr_create.yml
> +      CREATOR_ACCESS_TOKEN:
[HDA-10071 refactor: CREATOR_ACCESS_TOKEN -> PERSONAL_ACCESS_TOKEN](https://github.com/PRNDcompany/prnd-android-workflows/pull/37/commits/166ac3fca383d84e2f45eabb3961f2a9632496a6)

2023-09-08 01:01 UTC, ted-prnd approved these changes
LGTM 👍:ok_woman::pray::computer:

2023-09-08 01:25 UTC, merged